In [50]:
# Dependencies
import os 
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress 

#Reading in Files
cdc_df = pd.read_csv("Resource/VSRR_Provisional_Drug_Overdose_Death_Counts_2015_2021.csv")
care_df = pd.read_csv("Resource/Medicare_Opioid_Prescribing_Data_2013_2019.csv", low_memory = False)
caid_df = pd.read_csv("Resource/Medicaid_Opioid_Prescribing_data_2013_2019.csv", low_memory = False)

In [51]:
# Filtering Medcaid dropping year 2013 & 2014 and filtering for all plan types
caid_year = caid_df.loc[(caid_df["Year"] != 2013) & (caid_df["Year"] != 2014)]

caid_clean = caid_year.loc[caid_year["Plan_Type"]=="All"]

In [52]:
# Changing column name to state for merging later
caid_clean = caid_clean.rename(columns={"Geo_Desc":"State"})

caid_clean

,Year,Geo_Lvl,Geo_Cd,State,Plan_Type,Tot_Opioid_Clms,Tot_Clms,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg
0,2019,National,NaN,National,All,21978286.0,677248025.0,3.25,-3.22,-0.44,3108845.0,14.15,6.67,4.62
3,2019,State,1.0,Alabama,All,224310.0,7230251.0,3.10,-3.23,-1.08,10308.0,4.60,0.16,0.48
6,2019,State,2.0,Alaska,All,65394.0,1434139.0,4.56,-3.33,-1.20,8268.0,12.64,0.88,-0.71
9,2019,State,4.0,Arizona,All,595206.0,14923326.0,3.99,-5.14,-0.75,44311.0,7.44,-2.79,-0.52
12,2019,State,5.0,Arkansas,All,216081.0,4999626.0,4.32,-3.12,-0.88,8129.0,3.76,-0.34,-1.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,2015,State,51.0,Virginia,All,583116.0,10186332.0,5.72,NaN,-0.62,42311.0,7.26,NaN,-0.26
768,2015,State,53.0,Washington,All,1136474.0,14016747.0,8.11,NaN,-0.89,106143.0,9.34,NaN,0.18
771,2015,State,54.0,West Virginia,All,520370.0,9293729.0,5.60,NaN,-1.30,25575.0,4.91,NaN,0.66
774,2015,State,55.0,Wisconsin,All,962286.0,11306189.0,8.51,NaN,-0.35,146248.0,15.20,NaN,1.04
777,2015,State,56.0,Wyoming,All,39088.0,534212.0,7.32,NaN,-0.48,3792.0,9.70,NaN,-0.49

In [53]:
caid_clean.dtypes

Year                                int64
Geo_Lvl                            object
Geo_Cd                            float64
State                              object
Plan_Type                          object
Tot_Opioid_Clms                   float64
Tot_Clms                          float64
Opioid_Prscrbng_Rate              float64
Opioid_Prscrbng_Rate_5Y_Chg       float64
Opioid_Prscrbng_Rate_1Y_Chg       float64
LA_Tot_Opioid_Clms                float64
LA_Opioid_Prscrbng_Rate           float64
LA_Opioid_Prscrbng_Rate_5Y_Chg    float64
LA_Opioid_Prscrbng_Rate_1Y_Chg    float64
dtype: object

In [55]:
print(caid_clean['State'].unique())

['National' 'Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont'
 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']

AttributeError: 'NoneType' object has no attribute 'tolist'

In [36]:
caid_clean.groupby('Tot_Opioid_Clms').max()
caid_clean.head(50)

,Year,Geo_Lvl,Geo_Cd,State,Plan_Type,Tot_Opioid_Clms,Tot_Clms,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg
0,2019,National,NaN,National,All,21978286.0,677248025.0,3.25,-3.22,-0.44,3108845.0,14.15,6.67,4.62
3,2019,State,1.0,Alabama,All,224310.0,7230251.0,3.10,-3.23,-1.08,10308.0,4.60,0.16,0.48
6,2019,State,2.0,Alaska,All,65394.0,1434139.0,4.56,-3.33,-1.20,8268.0,12.64,0.88,-0.71
9,2019,State,4.0,Arizona,All,595206.0,14923326.0,3.99,-5.14,-0.75,44311.0,7.44,-2.79,-0.52
12,2019,State,5.0,Arkansas,All,216081.0,4999626.0,4.32,-3.12,-0.88,8129.0,3.76,-0.34,-1.05
15,2019,State,6.0,California,All,2760295.0,86344996.0,3.20,-3.12,-0.58,173985.0,6.30,-0.07,-0.18
18,2019,State,8.0,Colorado,All,419272.0,7572735.0,5.54,-5.56,-1.14,38808.0,9.26,1.03,0.01
21,2019,State,9.0,Connecticut,All,294479.0,9252048.0,3.18,-3.56,-0.34,22998.0,7.81,-1.70,0.81
24,2019,State,10.0,Delaware,All,90208.0,2786630.0,3.24,-4.65,-0.90,14353.0,15.91,-0.96,-0.72
27,2019,State,11.0,District of Columbia,All,59206.0,2132877.0,2.78,-2.33,-0.57,2366.0,4.00,-1.26,-0.23
30,2019,State,12.0,Florida,All,690384.0,26651687.0,2.59,-2.91,-0.58,49310.0,7.14,-1.22,0.08
33,2019,State,13.0,Georgia,All,596582.0,15438201.0,3.86,-2.80,-0.53,35192.0,5.90,0.93,-0.08
36,2019,State,15.0,Hawaii,All,86115.0,2204680.0,3.91,-3.48,-0.68,7898.0,9.17,-1.71,-1.25
39,2019,State,16.0,Idaho,All,84108.0,2322973.0,3.62,-4.25,-0.49,6667.0,7.93,-1.33,-0.57
42,2019,State,17.0,Illinois,All,816415.0,24662093.0,3.31,-2.73,-0.49,26261.0,3.22,-0.47,-0.12
45,2019,State,18.0,Indiana,All,544482.0,14856323.0,3.67,-4.40,-0.48,31333.0,5.75,-2.08,-0.19
48,2019,State,19.0,Iowa,All,222389.0,4665744.0,4.77,-1.75,0.20,117879.0,53.01,46.68,14.77
51,2019,State,20.0,Kansas,All,106495.0,3218036.0,3.31,-4.04,-1.22,8228.0,7.73,-2.35,-1.77
54,2019,State,21.0,Kentucky,All,662996.0,22211134.0,2.99,-2.03,-0.55,18036.0,2.72,-2.15,-0.32
57,2019,State,22.0,Louisiana,All,619940.0,19038465.0,3.26,-3.16,-0.64,14330.0,2.31,-0.93,0.20
60,2019,State,23.0,Maine,All,71943.0,2109869.0,3.41,-2.96,-0.36,10105.0,14.05,1.56,-1.20
63,2019,State,24.0,Maryland,All,517087.0,13666287.0,3.78,-3.46,-0.52,53606.0,10.37,0.46,-0.37
66,2019,State,25.0,Massachusetts,All,368831.0,16426950.0,2.25,-3.30,-0.37,35364.0,9.59,0.91,0.01
69,2019,State,26.0,Michigan,All,1038455.0,27368982.0,3.79,-5.18,-0.85,58585.0,5.64,-0.14,-0.11
72,2019,State,27.0,Minnesota,All,320765.0,11420217.0,2.81,-3.66,-0.56,25451.0,7.93,0.27,-0.06
75,2019,State,28.0,Mississippi,All,197700.0,5371695.0,3.68,-3.60,-0.85,9269.0,4.69,1.19,0.04
78,2019,State,29.0,Missouri,All,354685.0,10936865.0,3.24,-3.40,-0.73,28104.0,7.92,-0.80,-1.24
81,2019,State,30.0,Montana,All,300500.0,3050636.0,9.85,1.70,0.37,181069.0,60.26,48.90,9.53
84,2019,State,31.0,Nebraska,All,75085.0,2414233.0,3.11,-3.06,-0.81,8796.0,11.71,2.25,-0.55
87,2019,State,32.0,Nevada,All,294282.0,6326556.0,4.65,-5.17,-0.62,24945.0,8.48,-0.31,-0.59
90,2019,State,33.0,New Hampshire,All,46089.0,1801094.0,2.56,-3.72,-0.08,6474.0,14.05,-0.09,-0.20
93,2019,State,34.0,New Jersey,All,495531.0,18770567.0,2.64,-2.44,-0.31,41545.0,8.38,-0.02,-0.35
96,2019,State,35.0,New Mexico,All,202077.0,5011892.0,4.03,-3.78,-0.65,7305.0,3.62,-2.23,-0.27
99,2019,State,36.0,New York,All,1138716.0,65624447.0,1.74,-1.51,-0.26,89826.0,7.89,-1.24,-0.51
102,2019,State,37.0,North Carolina,All,520458.0,15521594.0,3.35,-3.98,-0.65,59423.0,11.42,2.24,0.42
105,2019,State,38.0,North Dakota,All,29732.0,953771.0,3.12,-4.18,-0.71,942.0,3.17,-4.52,-1.17
108,2019,State,39.0,Ohio,All,1063364.0,42151253.0,2.52,-4.61,-0.48,54719.0,5.15,-0.14,-0.21
111,2019,State,40.0,Oklahoma,All,236836.0,5357129.0,4.42,-3.91,-0.97,19148.0,8.08,1.03,-0.82
114,2019,State,41.0,Oregon,All,381857.0,9174669.0,4.16,-5.29,-0.69,40879.0,10.71,2.78,4.44
117,2019,State,42.0,Pennsylvania,All,617653.0,32338095.0,1.91,-4.46,-0.83,60010.0,9.72,0.74,0.57
120,2019,State,44.0,Rhode Island,All,71370.0,3172796.0,2.25,-3.38,-0.27,5817.0,8.15,2.09,0.50
123,2019,State,45.0,South Carolina,All,178209.0,6450845.0,2.76,-4.35,-0.80,12930.0,7.26,1.38,-0.06
126,2019,State,46.0,South Dakota,All,26420.0,868823.0,3.04,-3.68,-0.67,2627.0,9.94,2.06,-0.04
129,2019,State,47.0,Tennessee,All,334522.0,13730302.0,2.44,-5.21,-0.98,12306.0,3.68,-4.19,-0.50
132,2019,State,48.0,Texas,All,731329.0,29780435.0,2.46,-2.05,-0.41,32193.0,4.40,0.11,-0.43
135,2019,State,49.0,Utah,All,113115.0,2622443.0,4.31,-3.76,-0.51,10834.0,9.58,-0.37,-0.79
138,2019,State,50.0,Vermont,All,47131.0,1466306.0,3.21,-4.93,-0.83,6938.0,14.72,0.57,-0.44
141,2019,State,51.0,Virginia,All,1752577.0,16919491.0,10.36,4.02,3.81,1409828.0,80.44,72.92,16.73
144,2019,State,53.0,Washington,All,575330.0,14081168.0,4.09,-4.91,-0.93,47042.0,8.18,-0.98,0.27
147,2019,State,54.0,West Virginia,All,198673.0,9246096.0,2.15,-4.75,-0.58,7602.0,3.83,-0.42,-0.21

In [56]:
print(care_clean['State'].unique())

['National' 'Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont'
 'Virginia' 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming'
 'American Samoa' 'Guam' 'Northern Mariana Islands' 'Puerto Rico'
 'Virgin Islands']

In [22]:
# Filtering Medicaid Data by Breakout Type and Perscription Geographic Levels for National or State levels
care_year = care_df.loc[(care_df["Year"] != 2013) & (care_df["Year"] != 2014)]

care_clean = care_year.loc[(care_year["Breakout_Type"]=="Totals") & (care_year["Prscrbr_Geo_Lvl"]=="National") | (care_year["Prscrbr_Geo_Lvl"]=="State")]

In [23]:
# Changing column name to state for merging late
care_clean = care_clean.rename(columns={"Prscrbr_Geo_Desc":"State"})

care_clean

,Year,Prscrbr_Geo_Lvl,Prscrbr_Geo_Cd,State,RUCA_Cd,Breakout_Type,Breakout,Tot_Prscrbrs,Tot_Opioid_Prscrbrs,Tot_Opioid_Clms,Tot_Clms,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg
0,2019,National,NaN,National,NaN,Totals,Overall,1239380.0,803549.0,66138200.0,1.501140e+09,4.41,-1.32,-0.27,7290510.0,11.02,-1.73,-0.77
3,2019,State,1.0,Alabama,NaN,Totals,Overall,15575.0,9739.0,1814583.0,2.800821e+07,6.48,-1.40,-0.42,138456.0,7.63,-2.13,-0.73
4,2019,State,2.0,Alaska,NaN,Totals,Overall,2847.0,1935.0,80311.0,1.639104e+06,4.90,-2.01,-0.90,13005.0,16.19,-3.73,-2.42
5,2019,State,4.0,Arizona,NaN,Totals,Overall,25876.0,16578.0,1359955.0,2.569376e+07,5.29,-1.79,-0.33,184250.0,13.55,-2.58,-1.25
6,2019,State,5.0,Arkansas,NaN,Totals,Overall,9700.0,7258.0,998319.0,1.789430e+07,5.58,-1.08,-0.32,76135.0,7.63,-1.69,-0.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120121,2015,State,60.0,American Samoa,NaN,Rural/Urban,Urban,0.0,0.0,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120122,2015,State,66.0,Guam,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.000000e+00,NaN,NaN,NaN,0.0,NaN,NaN,NaN
120123,2015,State,69.0,Northern Mariana Islands,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120124,2015,State,72.0,Puerto Rico,NaN,Rural/Urban,Urban,10416.0,6946.0,438797.0,2.743746e+07,1.60,NaN,-0.67,13865.0,3.16,NaN,0.62
120125,2015,State,78.0,Virgin Islands,NaN,Rural/Urban,Urban,0.0,0.0,0.0,0.000000e+00,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [24]:
cdc_df

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Footnote,Footnote Symbol,Predicted Value
0,AK,2015,April,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
1,AK,2015,April,12 month-ending,Cocaine (T40.5),NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,126
4,AK,2015,April,12 month-ending,Psychostimulants with abuse potential (T43.6),NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44689,YC,2021,May,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)","1,792",100,0.298805,New York City,Underreported due to incomplete data.,*,"1,864"
44690,YC,2021,May,12 month-ending,Percent with drugs specified,99.2307692307692,100,0.298805,New York City,Underreported due to incomplete data.,*,NaN
44691,YC,2021,May,12 month-ending,Number of Deaths,"62,248",100,0.298805,New York City,Underreported due to incomplete data.,*,NaN
44692,YC,2021,May,12 month-ending,Cocaine (T40.5),962,100,0.298805,New York City,Underreported due to incomplete data.,*,"1,005"
44693,YC,2021,May,12 month-ending,Natural & semi-synthetic opioids (T40.2),469,100,0.298805,New York City,Underreported due to incomplete data.,*,485

In [30]:
print(cdc_year['Indicator'].unique())

['Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)'
 'Cocaine (T40.5)' 'Natural & semi-synthetic opioids (T40.2)'
 'Number of Drug Overdose Deaths'
 'Psychostimulants with abuse potential (T43.6)'
 'Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)'
 'Number of Deaths' 'Opioids (T40.0-T40.4,T40.6)'
 'Percent with drugs specified'
 'Synthetic opioids, excl. methadone (T40.4)' 'Heroin (T40.1)'
 'Methadone (T40.3)']

In [25]:
# Dropping years 2020 & 2021 and filtering indicator column 
cdc_year = cdc_df.loc[(cdc_df["Year"] != 2020) & (cdc_df["Year"] != 2021)]

cdc_indicator = cdc_year.loc[(cdc_year["Indicator"]=="Number of Drug Overdose Deaths") | (cdc_year["Indicator"]=="Number of Deaths") | (cdc_year["Indicator"]=="Natural & semi-synthetic opioids (T40.2)") | (cdc_year["Indicator"]=="Synthetic opioids, excl. methadone (T40.4)")]

In [26]:
# Changing column names for merging later
cdc_indicator = cdc_indicator.rename(columns={"State" : "State ID", "State Name" : "State"})

cdc_indicator

,State ID,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State,Footnote,Footnote Symbol,Predicted Value
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,126
6,AK,2015,April,12 month-ending,Number of Deaths,"4,133",100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
9,AK,2015,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
15,AK,2015,August,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44465,YC,2019,October,12 month-ending,Number of Deaths,"54,386",100,0.058839,New York City,Numbers may differ from published reports usin...,**,NaN
44466,YC,2019,September,12 month-ending,Natural & semi-synthetic opioids (T40.2),251,100,0.055099,New York City,Numbers may differ from published reports usin...,**,253
44472,YC,2019,September,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",893,100,0.055099,New York City,Numbers may differ from published reports usin...,**,898
44473,YC,2019,September,12 month-ending,Number of Drug Overdose Deaths,"1,457",100,0.055099,New York City,Numbers may differ from published reports usin...,**,"1,460"
44477,YC,2019,September,12 month-ending,Number of Deaths,"54,447",100,0.055099,New York City,Numbers may differ from published reports usin...,**,NaN

In [62]:
print(cdc_indicator.count())

State ID                         11880
Year                             11880
Month                            11880
Period                           11880
Indicator                        11880
Data Value                       10197
Percent Complete                 11880
Percent Pending Investigation    11880
State                            11880
Footnote                         11880
Footnote Symbol                  11880
Predicted Value                   7046
dtype: int64

In [70]:
cdc_indicator.dtypes

State ID                          object
Year                               int64
Month                             object
Period                            object
Indicator                         object
Data Value                        object
Percent Complete                  object
Percent Pending Investigation    float64
State                             object
Footnote                          object
Footnote Symbol                   object
Predicted Value                   object
dtype: object

In [75]:
cdc_indicator['Data Value'] = pd.to_numeric(cdc_indicator['Data Value'], errors = 'coerce')
cdc_indicator
#df['column'] = pd.to_numeric(df['column'],errors = 'coerce')

,State ID,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State,Footnote,Footnote Symbol,Predicted Value
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126.0,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,126
6,AK,2015,April,12 month-ending,Number of Deaths,NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
9,AK,2015,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
15,AK,2015,August,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",NaN,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44465,YC,2019,October,12 month-ending,Number of Deaths,NaN,100,0.058839,New York City,Numbers may differ from published reports usin...,**,NaN
44466,YC,2019,September,12 month-ending,Natural & semi-synthetic opioids (T40.2),251.0,100,0.055099,New York City,Numbers may differ from published reports usin...,**,253
44472,YC,2019,September,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",893.0,100,0.055099,New York City,Numbers may differ from published reports usin...,**,898
44473,YC,2019,September,12 month-ending,Number of Drug Overdose Deaths,NaN,100,0.055099,New York City,Numbers may differ from published reports usin...,**,"1,460"
44477,YC,2019,September,12 month-ending,Number of Deaths,NaN,100,0.055099,New York City,Numbers may differ from published reports usin...,**,NaN

In [79]:
cdc_indicator_group = cdc_indicator.groupby(['State ID', 'Year']).agg({'Data Value' : ['sum']}).reset_index()

cdc_indicator_group
#df.groupby(['team', 'position']).agg({'assists': ['mean']}).reset_index()

    State ID  Year Data Value
                          sum
0         AK  2015     1601.0
1         AK  2016     2380.0
2         AK  2017     2325.0
3         AK  2018     2234.0
4         AK  2019     2293.0
..       ...   ...        ...
260       YC  2015    13415.0
261       YC  2016     8852.0
262       YC  2017    12273.0
263       YC  2018    13588.0
264       YC  2019    12699.0

[265 rows x 3 columns]

In [82]:
Alaska = cdc_indicator_group.loc[cdc_indicator_group["State ID"]=="AK"]
Alaska

  State ID  Year Data Value
                        sum
0       AK  2015     1601.0
1       AK  2016     2380.0
2       AK  2017     2325.0
3       AK  2018     2234.0
4       AK  2019     2293.0

In [27]:
# Merging Medicaid & Medicare data with an Outer Join
insurance = pd.merge(care_clean, caid_clean, how = "outer")
insurance

,Year,Prscrbr_Geo_Lvl,Prscrbr_Geo_Cd,State,RUCA_Cd,Breakout_Type,Breakout,Tot_Prscrbrs,Tot_Opioid_Prscrbrs,Tot_Opioid_Clms,...,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg,Geo_Lvl,Geo_Cd,Plan_Type
0,2019,National,NaN,National,NaN,Totals,Overall,1239380.0,803549.0,66138200.0,...,4.41,-1.32,-0.27,7290510.0,11.02,-1.73,-0.77,NaN,NaN,NaN
1,2019,State,1.0,Alabama,NaN,Totals,Overall,15575.0,9739.0,1814583.0,...,6.48,-1.40,-0.42,138456.0,7.63,-2.13,-0.73,NaN,NaN,NaN
2,2019,State,2.0,Alaska,NaN,Totals,Overall,2847.0,1935.0,80311.0,...,4.90,-2.01,-0.90,13005.0,16.19,-3.73,-2.42,NaN,NaN,NaN
3,2019,State,4.0,Arizona,NaN,Totals,Overall,25876.0,16578.0,1359955.0,...,5.29,-1.79,-0.33,184250.0,13.55,-2.58,-1.25,NaN,NaN,NaN
4,2019,State,5.0,Arkansas,NaN,Totals,Overall,9700.0,7258.0,998319.0,...,5.58,-1.08,-0.32,76135.0,7.63,-1.69,-0.93,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100,2015,NaN,NaN,Virginia,NaN,NaN,NaN,NaN,NaN,583116.0,...,5.72,NaN,-0.62,42311.0,7.26,NaN,-0.26,State,51.0,All
1101,2015,NaN,NaN,Washington,NaN,NaN,NaN,NaN,NaN,1136474.0,...,8.11,NaN,-0.89,106143.0,9.34,NaN,0.18,State,53.0,All
1102,2015,NaN,NaN,West Virginia,NaN,NaN,NaN,NaN,NaN,520370.0,...,5.60,NaN,-1.30,25575.0,4.91,NaN,0.66,State,54.0,All
1103,2015,NaN,NaN,Wisconsin,NaN,NaN,NaN,NaN,NaN,962286.0,...,8.51,NaN,-0.35,146248.0,15.20,NaN,1.04,State,55.0,All
1104,2015,NaN,NaN,Wyoming,NaN,NaN,NaN,NaN,NaN,39088.0,...,7.32,NaN,-0.48,3792.0,9.70,NaN,-0.49,State,56.0,All

In [38]:
print(insurance['RUCA_Cd'].unique())

[nan]

In [28]:
# Merging CDC data & Insurace Data w/ an outer join and on Year and State
data = pd.merge(cdc_indicator, insurance, how = "outer", on = ["Year", "State"])

data

,State ID,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State,Footnote,...,Opioid_Prscrbng_Rate,Opioid_Prscrbng_Rate_5Y_Chg,Opioid_Prscrbng_Rate_1Y_Chg,LA_Tot_Opioid_Clms,LA_Opioid_Prscrbng_Rate,LA_Opioid_Prscrbng_Rate_5Y_Chg,LA_Opioid_Prscrbng_Rate_1Y_Chg,Geo_Lvl,Geo_Cd,Plan_Type
0,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,...,6.81,NaN,-0.10,18217.0,19.96,NaN,0.04,NaN,NaN,NaN
1,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,...,7.99,NaN,0.24,8974.5,23.11,NaN,1.72,NaN,NaN,NaN
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,...,6.13,NaN,-0.27,10617.0,20.26,NaN,-1.04,NaN,NaN,NaN
3,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,...,7.61,NaN,-0.28,9048.0,12.32,NaN,0.56,State,2.0,All
4,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126,100,0.0,Alaska,Numbers may differ from published reports usin...,...,6.81,NaN,-0.10,18217.0,19.96,NaN,0.04,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46160,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,Puerto Rico,NaN,...,2.10,NaN,-0.60,415.0,3.20,NaN,1.29,NaN,NaN,NaN
46161,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,Puerto Rico,NaN,...,1.60,NaN,-0.67,13865.0,3.16,NaN,0.62,NaN,NaN,NaN
46162,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,Virgin Islands,NaN,...,1.67,NaN,-0.15,204.0,5.75,NaN,1.22,NaN,NaN,NaN
46163,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,Virgin Islands,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
46164,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,Virgin Islands,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
print(data.count())

State ID                          46080
Year                              46165
Month                             46080
Period                            46080
Indicator                         46080
Data Value                        39348
Percent Complete                  46080
Percent Pending Investigation     46080
State                             46165
Footnote                          46080
Footnote Symbol                   46080
Predicted Value                   27104
Prscrbr_Geo_Lvl                   34280
Prscrbr_Geo_Cd                    34275
RUCA_Cd                               0
Breakout_Type                     34280
Breakout                          34280
Tot_Prscrbrs                      34280
Tot_Opioid_Prscrbrs               34280
Tot_Opioid_Clms                   45682
Tot_Clms                          45685
Opioid_Prscrbng_Rate              45164
Opioid_Prscrbng_Rate_5Y_Chg       15785
Opioid_Prscrbng_Rate_1Y_Chg       45163
LA_Tot_Opioid_Clms                45670
LA_Opioid_Prscrbng_Rate           45159
LA_Opioid_Prscrbng_Rate_5Y_Chg    15782
LA_Opioid_Prscrbng_Rate_1Y_Chg    45157
Geo_Lvl                           11405
Geo_Cd                            11400
Plan_Type                         11405
dtype: int64